services:
  family_plan_server:
    container_name: family_plan_server
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./.env:/app/.env
