name: CI/CD AMD64 Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build & Push AMD64 Image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push AMD64 image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: ghcr.io/${{ github.repository_owner }}/family-plan:latest

  # deploy:
  #   name: Deploy to Self-Hosted AMD64
  #   runs-on: [self-hosted, linux, amd64]
  #   needs: build

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4

  #     - name: Log in to GHCR
  #       uses: docker/login-action@v3
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.GITHUB_TOKEN }}

  #     - name: Deploy with Docker Compose & Run Migrations
  #       run: |
  #         cd /home/ndik/stacks/family-plan
  #         docker compose pull
  #         docker compose up -d
  #         docker compose exec -T family_plan_server php artisan migrate --force
