name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository_owner }}/family-plan:latest
            ghcr.io/${{ github.repository_owner }}/family-plan:${{ github.sha }}

  # deploy:
  #   runs-on: self-hosted
  #   needs: build
  #   steps:
  #     - name: Pull latest image
  #       run: |
  #         echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
  #         docker pull ghcr.io/${{ github.repository_owner }}/family-plan:latest

  #     - name: Deploy container
  #       run: |
  #         docker stop family-plan || true
  #         docker rm family-plan || true
  #         docker run -d --name family-plan -p 3000:3000 ghcr.io/${{ github.repository_owner }}/family-plan:latest
