name: CI/CD Multi-Arch Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_arm64:
    name: Build ARM64 (self-hosted)
    runs-on: [self-hosted, linux, arm64]

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build ARM64 Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/family-plan:arm64 .
          docker push ghcr.io/${{ github.repository_owner }}/family-plan:arm64

      - name: Deploy with Docker Compose
        run: |
          cd /home/ndik/stacks/family-plan
          docker compose pull
          docker compose up -d

      - name: Run Laravel migrations
        run: |
          cd /home/ndik/stacks/family-plan
          docker-compose exec -T family_plan_server php artisan migrate --force

  build_amd64:
    name: Build AMD64 (GitHub-hosted)
    runs-on: ubuntu-latest
    needs: build_arm64

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build AMD64 Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: ghcr.io/${{ github.repository_owner }}/family-plan:amd64

      - name: Create multi-arch latest tag
        run: |
          docker buildx imagetools create \
            --tag ghcr.io/${{ github.repository_owner }}/family-plan:latest \
            ghcr.io/${{ github.repository_owner }}/family-plan:amd64 \
            ghcr.io/${{ github.repository_owner }}/family-plan:arm64